// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kakeibo3.Models;

namespace kakeibo3.Migrations
{
    [DbContext(typeof(kakeibo3Context))]
    partial class kakeibo3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kakeibo3.Models.CashRow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CostType");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ForMonth");

                    b.Property<DateTime>("PayDate");

                    b.Property<string>("PayItem");

                    b.Property<string>("Payer");

                    b.Property<string>("Payment");

                    b.Property<int>("Price");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.ToTable("CashRow");
                });
#pragma warning restore 612, 618
        }
    }
}
